import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import HeaderHome from "@/components/header-home";
import FooterHome from "@/components/footer-home";
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
			 	className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
			>
				<div className="flex flex-col min-h-screen">
					<HeaderHome />
						<main className="flex-1 p-4 bg-[url('/purple.jpg')] bg-cover bg-center">{children}</main>
					<FooterHome />
				</div>
			</body>
			<Toaster />
		</html>
	);
}
